---
title: "maria_ignacio_flow"
author: "Sam Bankston"
date: "December 11, 2018"
output:
  html_document: default
  pdf_document: default
---

Load packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```

Read in data

```{r message=FALSE, warning=FALSE}
all_flow <- read_csv("maria_ygnacio_flow.csv") %>% mutate(date_time = paste(Date, " ", Time), date_time = mdy_hms(date_time)) %>% rename(flow = Flow) %>% select(date_time, flow) %>% mutate(Day = date(date_time), Year = year(date_time))

```

Summary of daily flow values

```{r}
daily_flow_summary <- all_flow %>% filter(month(date_time) >= 1 & month(date_time) < 6) %>% group_by(Year, Day) %>% summarize(mean_daily_flow = mean(flow, na.rm = TRUE)) %>% ungroup()
```

Calculate low and high flow thresholds

```{r}
low_high <- daily_flow_summary %>% summarize(low_flow = quantile(daily_flow_summary$mean_daily_flow, probs = .50, na.rm = TRUE), high_flow = quantile(daily_flow_summary$mean_daily_flow, probs = 0.99, na.rm = TRUE)) %>% print()
```

top 20 mean daily flow values

```{r}
top_20 <- daily_flow_summary %>% top_n(n = 20, wt = mean_daily_flow) %>% arrange(desc(mean_daily_flow)) 

top_20
```

histogram of mean daily flow

```{r message=FALSE, warning=FALSE}
daily_flow_summary %>% ggplot(aes(x = mean_daily_flow)) + geom_histogram() + theme_bw()
```

Flow summary statistics

```{r}
mean_daily_flow <- mean(daily_flow_summary$mean_daily_flow, na.rm = TRUE) %>% print()

percent_days_zero <- mean(daily_flow_summary$mean_daily_flow == "0") %>% print()

num_days_zero <- sum(daily_flow_summary$mean_daily_flow == "0") %>% print()

num_days_total <- n_distinct(daily_flow_summary$Day) %>% print()


```



